version: "3.8"

services:
  redis:
    image: redis:alpine
    container_name: redis_db
    restart: always
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: url_shortener
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - Durl=http://localhost:8080/
      - REDIS_ADDR=redis:6379
      - DB_URL="postgresql://neondb_owner:npg_3yAVSZ7CLefq@ep-long-bonus-a8t1sjn8-pooler.eastus2.azure.neon.tech/neondb?sslmode=require"
